  0%|                                                                                                                                                                                                                  | 0/3100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\Olivier\Documents\GitHub\ssmh4\task6-refactor\main.py", line 135, in <module>
    main(args.config)
  File "C:\Users\Olivier\Documents\GitHub\ssmh4\task6-refactor\main.py", line 98, in main
    trainer.train()
  File "C:\Users\Olivier\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olivier\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 2556, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olivier\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 3718, in training_step
    loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CustomVAEMTrainer.compute_loss() got an unexpected keyword argument 'num_items_in_batch'
